### ISSUE TITLE
Recent change in Hyper seems to break the example hyper code due to TLS

### ISSUE THREAD

**Issue by tg339** [kuchiki-rs/kuchiki#32]
Running the example code returns an invalid scheme for HTTP error. 

http://stackoverflow.com/questions/41619187/hyper-says-invalid-scheme-for-http-for-https-urls

Fix seems pretty simple. Will pull create PR. It adds a dependency on this crate though https://docs.rs/hyper-native-tls/0.2.2/hyper_native_tls/

**Comment by SimonSapin** [comment]
If the example is to be fixed, I’d rather switch it to an HTTP URL to avoid requiring a TLS dependency just for that example. However, I’m also considering removing Hyper support since the only valuable part of it is:

```rust
        let opts = BytesOpts {
            transport_layer_encoding: response.headers.get::<ContentType>()
                .and_then(|content_type| content_type.get_param(Charset))
                .and_then(|charset| encoding_from_whatwg_label(charset))
        };
```

Which can easily enough be documented, and can be skipped if you know the encoding to be UTF-8.

Additionally, upcoming changes to html5ever might make `BytesOpts` obsolete so all of Kuchiki’s input handling will need to be reworked anyway…

**Comment by tg339** [comment]
I think documentation and removal is probably the most logical thing to do.

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
