### ISSUE TITLE
Shareable (Send) Document

### ISSUE THREAD

**Issue by theduke** [kuchiki-rs/kuchiki#44]
I'm currently writing a media application where users are able to extract data from html pages with custom scripts written in [Gluon](https://github.com/gluon-lang/gluon).

Gluon makes it pretty easy to access Rust data types, but they must be `Send`.

The html5ever/kuchiki nodes use Rc<> and so can't be send. 

I've come up with two alternatives that sort of make this work, but they are both ridiculously ugly hacks. (a: have a dedicated parser thread that owns the dom and handles queries with channel communication; b) re-parse on each query and return custom nodes that don't use Rc).

Do you see any alternative of how I could make this more sensible?

This would obviously be easier with arena style allocation, but kuchiki has the dom hard-coded so I don't see that happening.

**Comment by SimonSapin** [comment]
With reference counting you can have multiple references/handles to the same node. So for such a handle to be `Send`, nodes (and therefore other handles) need to be `Sync` as well.

The "classic" thread-safe alternative to `Rc` + `RefCell` is `Arc` + `Mutex` (or `RwLock`). However in addition to being potentially very slow, there’s also the problem that even with `Arc` "links" between nodes many (all?) tree operations are not atomic because they involve updating multiple links. So while a thread is modifying the tree, another thread could potentially find it in an inconsistent state. I don’t know if such inconsistent state could cause a memory safety issue (probably not, there’s not a lot of `unsafe` code in Kuchiki) but I think it would definitely cause problems that manifest as incorrect behavior or panics.

Maybe a document-wide shared `RwLock` could work? It would solve the state consistency issues, and possibly have less lock contention than per-node locks too.

But then if you don’t actually need to modify the document you can probably get away with less synchronization than that. Mutation is still needed during initial parsing (to set up e.g. parent links), so maybe there could be a set of single-thread mutable data-structures that are then unsafely transmuted into immutable thread-safe data structures. They’d need to have the exact same memory layout, so generics with phantom types might help there. As you mentioned, an arena allocator would likely help here.

Or, if you don’t need "back links" (going from a node to its parent, etc.) you could have a tree with "classic" Rust ownership, something like `struct Node { children: Vec<Node>, … }`, such that you could first do mutation / initial parsing with `&mut Node` exclusive references on a single thread, and then send `&Node` shared references to scoped threads (or move the root into an `Arc<Node>`).

----

The above mentions a few possible leads, but all of them involve making a different tree data structure. Which means it wouldn’t be Kuchiki anymore, since the tree data structure is pretty much all there is to it.

I think that Rust’s ownership/borrowing/thread-safety semantics mean that it might not be possible to make a single definitive library in the style of Nokogiri or lxml that could cover many use cases. Instead, different use cases might want to make different trade-offs that lead to different tree data structures. I like to this of Kuchiki as a proof-of-concept or an example of how the `html5ever` and `selectors` crates can be glued together, and I would encourage you to experiment with writing your own.

(For example in my experiments at https://github.com/SimonSapin/victor I use arena-allocated nodes because, in non-interactive processing with no tree mutation after the initial parsing, all nodes in the document would be dropped around the same time anyway.)

**Comment by SimonSapin** [comment]
> Or, if you don’t need "back links" (going from a node to its parent, etc.)

Note that implementations of the `selectors` crate that I know of need such back links (for example to match descendant selectors like `body h1`). I’ve been pondering whether it would possible to remove this need by, instead of only keeping a single reference to the current node when traversing the tree, keep a "cursor" (similar to what Haskell calls a "zipper", I think?) with a stack of all the ancestor elements since the root (and indices or iterators into the respective `Vec`s of child nodes, if they are used instead of links to sibling nodes).

**Comment by Roms1383** [comment]
I actually stumbled upon the same using [easy-scraper](https://crates.io/crates/easy-scraper) (which uses kuchiki [in its dependencies](https://crates.io/crates/easy-scraper/0.2.0/dependencies)) when trying to store it with [lazy_static](https://crates.io/crates/lazy_static).

`easy-scraper` allows to me to scrape many html pages and I just thought I could avoid recreating the [Pattern](https://docs.rs/easy-scraper/0.2.0/easy_scraper/struct.Pattern.html) which is being used with every page. But for my own little use case this is not a big deal though since I can utterly recreate the `Pattern` on each iteration.

<img width="980" alt="Screen Shot 2564-09-15 at 18 51 42" src="https://user-images.githubusercontent.com/21016014/133429387-a927b976-e27f-496c-8097-0e1ce9ac1a56.png">

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this issue will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived
